version: '3'
services:
  app:
    build: .
    volumes:
      - ./data:/app/data
      - ./db:/app/db
    environment:
      - START_DATE=2022-12-01
      - END_DATE=2022-12-31
    # Allocate a TTY for the container
    tty: true
    stdin_open: true
